spring:
  application:
    name: invoice
  datasource:
    url: jdbc:postgresql://localhost:5433/invoice_db
    username: user
    password: secret

logging:
  level:
    org.flywaydb: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,flyway
  endpoint:
    health:
      show-details: always

vaadin:
  launch-browser: false
